// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: jasmine.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseGetGeoJson struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string                         `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Features []*ResponseGetGeoJson_Features `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`
}

func (x *ResponseGetGeoJson) Reset() {
	*x = ResponseGetGeoJson{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jasmine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetGeoJson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetGeoJson) ProtoMessage() {}

func (x *ResponseGetGeoJson) ProtoReflect() protoreflect.Message {
	mi := &file_jasmine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetGeoJson.ProtoReflect.Descriptor instead.
func (*ResponseGetGeoJson) Descriptor() ([]byte, []int) {
	return file_jasmine_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetGeoJson) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResponseGetGeoJson) GetFeatures() []*ResponseGetGeoJson_Features {
	if x != nil {
		return x.Features
	}
	return nil
}

type RequestGet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket string `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
}

func (x *RequestGet) Reset() {
	*x = RequestGet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jasmine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGet) ProtoMessage() {}

func (x *RequestGet) ProtoReflect() protoreflect.Message {
	mi := &file_jasmine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGet.ProtoReflect.Descriptor instead.
func (*RequestGet) Descriptor() ([]byte, []int) {
	return file_jasmine_proto_rawDescGZIP(), []int{1}
}

func (x *RequestGet) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type ResponseGet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Riders []*Riders `protobuf:"bytes,1,rep,name=riders,proto3" json:"riders,omitempty"`
}

func (x *ResponseGet) Reset() {
	*x = ResponseGet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jasmine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGet) ProtoMessage() {}

func (x *ResponseGet) ProtoReflect() protoreflect.Message {
	mi := &file_jasmine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGet.ProtoReflect.Descriptor instead.
func (*ResponseGet) Descriptor() ([]byte, []int) {
	return file_jasmine_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseGet) GetRiders() []*Riders {
	if x != nil {
		return x.Riders
	}
	return nil
}

type Riders struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RiderId   string  `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	Latitude  float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Riders) Reset() {
	*x = Riders{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jasmine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Riders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Riders) ProtoMessage() {}

func (x *Riders) ProtoReflect() protoreflect.Message {
	mi := &file_jasmine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Riders.ProtoReflect.Descriptor instead.
func (*Riders) Descriptor() ([]byte, []int) {
	return file_jasmine_proto_rawDescGZIP(), []int{3}
}

func (x *Riders) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *Riders) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Riders) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type RequestNearby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket    string  `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty" validate:"required"`         // @gotags: validate:"required"
	Latitude  float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty" validate:"required,latitude"`   // @gotags: validate:"required,latitude"
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty" validate:"required,longitude"` // @gotags: validate:"required,longitude"
	Limit     uint32  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *RequestNearby) Reset() {
	*x = RequestNearby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jasmine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestNearby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNearby) ProtoMessage() {}

func (x *RequestNearby) ProtoReflect() protoreflect.Message {
	mi := &file_jasmine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNearby.ProtoReflect.Descriptor instead.
func (*RequestNearby) Descriptor() ([]byte, []int) {
	return file_jasmine_proto_rawDescGZIP(), []int{4}
}

func (x *RequestNearby) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *RequestNearby) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RequestNearby) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *RequestNearby) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ResponseNearby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rider []*RidersNearby `protobuf:"bytes,1,rep,name=rider,proto3" json:"rider,omitempty"`
}

func (x *ResponseNearby) Reset() {
	*x = ResponseNearby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jasmine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseNearby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseNearby) ProtoMessage() {}

func (x *ResponseNearby) ProtoReflect() protoreflect.Message {
	mi := &file_jasmine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseNearby.ProtoReflect.Descriptor instead.
func (*ResponseNearby) Descriptor() ([]byte, []int) {
	return file_jasmine_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseNearby) GetRider() []*RidersNearby {
	if x != nil {
		return x.Rider
	}
	return nil
}

type RidersNearby struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RiderId   string  `protobuf:"bytes,1,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty"`
	Latitude  float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Distance  float64 `protobuf:"fixed64,4,opt,name=distance,proto3" json:"distance,omitempty"`
}

func (x *RidersNearby) Reset() {
	*x = RidersNearby{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jasmine_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RidersNearby) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RidersNearby) ProtoMessage() {}

func (x *RidersNearby) ProtoReflect() protoreflect.Message {
	mi := &file_jasmine_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RidersNearby.ProtoReflect.Descriptor instead.
func (*RidersNearby) Descriptor() ([]byte, []int) {
	return file_jasmine_proto_rawDescGZIP(), []int{6}
}

func (x *RidersNearby) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *RidersNearby) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RidersNearby) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *RidersNearby) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type RequestStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bucket    string  `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty" validate:"required"`                  // @gotags: validate:"required"
	RiderId   string  `protobuf:"bytes,2,opt,name=rider_id,json=riderId,proto3" json:"rider_id,omitempty" validate:"required"` // @gotags: validate:"required"
	Latitude  float64 `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty" validate:"required,latitude"`            // @gotags: validate:"required,latitude"
	Longitude float64 `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty" validate:"required,longitude"`          // @gotags: validate:"required,longitude"
}

func (x *RequestStore) Reset() {
	*x = RequestStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jasmine_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStore) ProtoMessage() {}

func (x *RequestStore) ProtoReflect() protoreflect.Message {
	mi := &file_jasmine_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStore.ProtoReflect.Descriptor instead.
func (*RequestStore) Descriptor() ([]byte, []int) {
	return file_jasmine_proto_rawDescGZIP(), []int{7}
}

func (x *RequestStore) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *RequestStore) GetRiderId() string {
	if x != nil {
		return x.RiderId
	}
	return ""
}

func (x *RequestStore) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RequestStore) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ResponseStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ResponseStore) Reset() {
	*x = ResponseStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jasmine_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStore) ProtoMessage() {}

func (x *ResponseStore) ProtoReflect() protoreflect.Message {
	mi := &file_jasmine_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStore.ProtoReflect.Descriptor instead.
func (*ResponseStore) Descriptor() ([]byte, []int) {
	return file_jasmine_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseStore) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ResponseGetGeoJson_Properties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Markercolor  string `protobuf:"bytes,1,opt,name=markercolor,json=marker-color,proto3" json:"markercolor,omitempty"`
	Markersize   string `protobuf:"bytes,2,opt,name=markersize,json=marker-size,proto3" json:"markersize,omitempty"`
	Markersymbol string `protobuf:"bytes,3,opt,name=markersymbol,json=marker-symbol,proto3" json:"markersymbol,omitempty"`
}

func (x *ResponseGetGeoJson_Properties) Reset() {
	*x = ResponseGetGeoJson_Properties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jasmine_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetGeoJson_Properties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetGeoJson_Properties) ProtoMessage() {}

func (x *ResponseGetGeoJson_Properties) ProtoReflect() protoreflect.Message {
	mi := &file_jasmine_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetGeoJson_Properties.ProtoReflect.Descriptor instead.
func (*ResponseGetGeoJson_Properties) Descriptor() ([]byte, []int) {
	return file_jasmine_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ResponseGetGeoJson_Properties) GetMarkercolor() string {
	if x != nil {
		return x.Markercolor
	}
	return ""
}

func (x *ResponseGetGeoJson_Properties) GetMarkersize() string {
	if x != nil {
		return x.Markersize
	}
	return ""
}

func (x *ResponseGetGeoJson_Properties) GetMarkersymbol() string {
	if x != nil {
		return x.Markersymbol
	}
	return ""
}

type ResponseGetGeoJson_Geometry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinates []float64 `protobuf:"fixed64,1,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	Type        string    `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ResponseGetGeoJson_Geometry) Reset() {
	*x = ResponseGetGeoJson_Geometry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jasmine_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetGeoJson_Geometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetGeoJson_Geometry) ProtoMessage() {}

func (x *ResponseGetGeoJson_Geometry) ProtoReflect() protoreflect.Message {
	mi := &file_jasmine_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetGeoJson_Geometry.ProtoReflect.Descriptor instead.
func (*ResponseGetGeoJson_Geometry) Descriptor() ([]byte, []int) {
	return file_jasmine_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ResponseGetGeoJson_Geometry) GetCoordinates() []float64 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *ResponseGetGeoJson_Geometry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ResponseGetGeoJson_Features struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       string                         `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Properties *ResponseGetGeoJson_Properties `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	Geometry   *ResponseGetGeoJson_Geometry   `protobuf:"bytes,3,opt,name=geometry,proto3" json:"geometry,omitempty"`
	Id         uint32                         `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ResponseGetGeoJson_Features) Reset() {
	*x = ResponseGetGeoJson_Features{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jasmine_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetGeoJson_Features) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetGeoJson_Features) ProtoMessage() {}

func (x *ResponseGetGeoJson_Features) ProtoReflect() protoreflect.Message {
	mi := &file_jasmine_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetGeoJson_Features.ProtoReflect.Descriptor instead.
func (*ResponseGetGeoJson_Features) Descriptor() ([]byte, []int) {
	return file_jasmine_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ResponseGetGeoJson_Features) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResponseGetGeoJson_Features) GetProperties() *ResponseGetGeoJson_Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *ResponseGetGeoJson_Features) GetGeometry() *ResponseGetGeoJson_Geometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *ResponseGetGeoJson_Features) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_jasmine_proto protoreflect.FileDescriptor

var file_jasmine_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6a, 0x61, 0x73, 0x6d, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc6, 0x03,
	0x0a, 0x12, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6f,
	0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x66, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6f, 0x4a, 0x73, 0x6f, 0x6e, 0x2e,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x1a, 0x75, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x12, 0x21, 0x0a, 0x0b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x2d, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x12, 0x1f, 0x0a, 0x0a, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x2d,
	0x73, 0x69, 0x7a, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x72, 0x2d, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x1a, 0x40, 0x0a, 0x08, 0x47, 0x65, 0x6f,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x1a, 0xa8, 0x01, 0x0a, 0x08,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x0a,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x47, 0x65,
	0x6f, 0x4a, 0x73, 0x6f, 0x6e, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x08,
	0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6f, 0x4a,
	0x73, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x08, 0x67, 0x65,
	0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x24, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x47, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x2e, 0x0a, 0x0b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x06, 0x72,
	0x69, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x69,
	0x64, 0x65, 0x72, 0x73, 0x52, 0x06, 0x72, 0x69, 0x64, 0x65, 0x72, 0x73, 0x22, 0x5d, 0x0a, 0x06,
	0x52, 0x69, 0x64, 0x65, 0x72, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x69, 0x64, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x77, 0x0a, 0x0d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x35, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x12, 0x23, 0x0a, 0x05, 0x72, 0x69, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x72, 0x73, 0x4e, 0x65,
	0x61, 0x72, 0x62, 0x79, 0x52, 0x05, 0x72, 0x69, 0x64, 0x65, 0x72, 0x22, 0x7f, 0x0a, 0x0c, 0x52,
	0x69, 0x64, 0x65, 0x72, 0x73, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x72,
	0x69, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72,
	0x69, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75,
	0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x7b, 0x0a, 0x0c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x75,
	0x63, 0x6b, 0x65, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x69, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x27, 0x0a, 0x0d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x32, 0xa3, 0x02, 0x0a, 0x0f, 0x4a, 0x61, 0x73, 0x6d, 0x69, 0x6e, 0x65, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x3b, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x0b, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x1a, 0x0c,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x22, 0x15, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x67, 0x65, 0x74, 0x2f, 0x7b, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x7d, 0x12, 0x51, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x47, 0x65,
	0x6f, 0x4a, 0x73, 0x6f, 0x6e, 0x12, 0x0b, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47,
	0x65, 0x74, 0x1a, 0x13, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74,
	0x47, 0x65, 0x6f, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12,
	0x15, 0x2f, 0x67, 0x65, 0x74, 0x2f, 0x7b, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x7d, 0x2f, 0x67,
	0x65, 0x6f, 0x6a, 0x73, 0x6f, 0x6e, 0x12, 0x41, 0x0a, 0x0a, 0x50, 0x6f, 0x73, 0x74, 0x4e, 0x65,
	0x61, 0x72, 0x62, 0x79, 0x12, 0x0e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x65,
	0x61, 0x72, 0x62, 0x79, 0x1a, 0x0f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4e,
	0x65, 0x61, 0x72, 0x62, 0x79, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x3a, 0x01, 0x2a,
	0x22, 0x07, 0x2f, 0x6e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x12, 0x3d, 0x0a, 0x09, 0x50, 0x6f, 0x73,
	0x74, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x0d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x1a, 0x0e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x3a, 0x01, 0x2a,
	0x22, 0x06, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x73, 0x65, 0x70, 0x74, 0x69, 0x61, 0x61, 0x6e,
	0x2f, 0x6a, 0x61, 0x73, 0x6d, 0x69, 0x6e, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jasmine_proto_rawDescOnce sync.Once
	file_jasmine_proto_rawDescData = file_jasmine_proto_rawDesc
)

func file_jasmine_proto_rawDescGZIP() []byte {
	file_jasmine_proto_rawDescOnce.Do(func() {
		file_jasmine_proto_rawDescData = protoimpl.X.CompressGZIP(file_jasmine_proto_rawDescData)
	})
	return file_jasmine_proto_rawDescData
}

var file_jasmine_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_jasmine_proto_goTypes = []interface{}{
	(*ResponseGetGeoJson)(nil),            // 0: ResponseGetGeoJson
	(*RequestGet)(nil),                    // 1: RequestGet
	(*ResponseGet)(nil),                   // 2: ResponseGet
	(*Riders)(nil),                        // 3: Riders
	(*RequestNearby)(nil),                 // 4: RequestNearby
	(*ResponseNearby)(nil),                // 5: ResponseNearby
	(*RidersNearby)(nil),                  // 6: RidersNearby
	(*RequestStore)(nil),                  // 7: RequestStore
	(*ResponseStore)(nil),                 // 8: ResponseStore
	(*ResponseGetGeoJson_Properties)(nil), // 9: ResponseGetGeoJson.Properties
	(*ResponseGetGeoJson_Geometry)(nil),   // 10: ResponseGetGeoJson.Geometry
	(*ResponseGetGeoJson_Features)(nil),   // 11: ResponseGetGeoJson.Features
}
var file_jasmine_proto_depIdxs = []int32{
	11, // 0: ResponseGetGeoJson.features:type_name -> ResponseGetGeoJson.Features
	3,  // 1: ResponseGet.riders:type_name -> Riders
	6,  // 2: ResponseNearby.rider:type_name -> RidersNearby
	9,  // 3: ResponseGetGeoJson.Features.properties:type_name -> ResponseGetGeoJson.Properties
	10, // 4: ResponseGetGeoJson.Features.geometry:type_name -> ResponseGetGeoJson.Geometry
	1,  // 5: JasmineEndpoint.GetData:input_type -> RequestGet
	1,  // 6: JasmineEndpoint.GetDataGeoJson:input_type -> RequestGet
	4,  // 7: JasmineEndpoint.PostNearby:input_type -> RequestNearby
	7,  // 8: JasmineEndpoint.PostStore:input_type -> RequestStore
	2,  // 9: JasmineEndpoint.GetData:output_type -> ResponseGet
	0,  // 10: JasmineEndpoint.GetDataGeoJson:output_type -> ResponseGetGeoJson
	5,  // 11: JasmineEndpoint.PostNearby:output_type -> ResponseNearby
	8,  // 12: JasmineEndpoint.PostStore:output_type -> ResponseStore
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_jasmine_proto_init() }
func file_jasmine_proto_init() {
	if File_jasmine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jasmine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetGeoJson); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jasmine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jasmine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jasmine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Riders); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jasmine_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestNearby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jasmine_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseNearby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jasmine_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RidersNearby); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jasmine_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jasmine_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jasmine_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetGeoJson_Properties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jasmine_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetGeoJson_Geometry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jasmine_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetGeoJson_Features); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jasmine_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jasmine_proto_goTypes,
		DependencyIndexes: file_jasmine_proto_depIdxs,
		MessageInfos:      file_jasmine_proto_msgTypes,
	}.Build()
	File_jasmine_proto = out.File
	file_jasmine_proto_rawDesc = nil
	file_jasmine_proto_goTypes = nil
	file_jasmine_proto_depIdxs = nil
}
